professores = {
    "Taciana Pontal": ["PCO","IHM"],
    "Rodrigo Rosal": ["FED"],
    "Abner Barros": ["CIR","ARQ"],
    "Virginia Cavalcenti":["PSI"],
    "Arlley Antônio": ["PROD"],
    "George Cabral": ["PROG"],
    "Sheila Gomes": ["POL"],
    "Bárbara Costa": ["CAL1"],
    "Silas Carlos": ["PSI2"],
    "Rafael Dueire ": ["MD1"],
    "Maigan Stefanne":["MD2"],
    "Rinaldo José": ["BD"], 
    "Gustavo Callou":["PROG2"],
    "Jeane Melo":["ALG"],
    "José 1": ["CALC2"],
    "Jose 2":["DID"],
    "Antônio Sistelos": ["EST"],
    "Rozelma":["MEC"],
    "Pablo Sampaio":["TCO","SMA"],
    "Kellyton Brito": ["METC","GOVTI"],
    "Douglas Veras":["SO"],
    "JOSE ALAN":['AL'],
    "Jeísa Domingues":["REDES"],
    "Paulo Anselmo":["ESSI"],
    "Lucas Figueiredo":["TED"],
    "Jeneffer Ferreira":["PED"],
    "André Câmara":["IA"],
    "Wagner Lins ":["RET"],
    "Emerson Andrade":["EAD"],
    "Lucas Albertins":["POO"],
    "Janaina Sampaio":["LIB"],
    "Marcos Cardoso":["PSED"],
    "Ricardo Souza":["ER"],
}
